<html>
    <head>
        <title>Main website</title>
        <link rel="stylesheet" href="Main.css">
    </head>
<body>

     <!-- Header section -->
     <?php
    require("header.php");
    ?>

<main>

    <div class="about-container" >

        <div class="about-left">
            <h1> ABOUT US</h1>
            <p>
            Pen haven is a web-based application, which provides interface to a user.
            It is an online shopping of branded pens and purchasing using C.O.D
            (Cash on Delivery) for increasing the trust of online world among users.
            Using this web application, user find the best deals for their budget and
            get exclusively online deals with discount on festive season. Online
            shopping helps them to save their time also. The price point in online
            shopping is always less because there will be no intermediary in this
            system.</p>
            <br />
            <br />
            <p>
            This system will help customers and small workers to gain trust on
            online shopping system. Using online shopping system brands also
            increase their chain within our country and brands also trying to provide
            best deals for increase customer base. 
            </p>
        </div>

        <div class="about-right">
                <div id="about-right-content">
                    <img src="./cards_images/abhi.jpeg" alt="">
                    <h1>Abhishek Pandey</h1>
                </div>
        </div>
        
    </div>
    
    
    

      
    <div class="about-down-container" >
        <div class="about-down">
            <h1 style="text-align: left;">Terms of Use</h1>
            <p>

                This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                
                This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name [www.luxury-pen.com]<br><br>
                
                
                Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with Flipkart Internet Private Limited and these terms and conditions including the policies constitute Your binding obligations, with Luxury Pen- Ecommerce.<br><br>
                
                For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to become a buyer on the Platform by providing Registration Data while registering on the Platform as Registered User using the computer systems. Flipkart allows the User to surf the Platform or making purchases without registering on the Platform. The term "We", "Us", "Our" shall mean Luxury Pen- Ecommerce Internet Private Limited.<br><br>
                
                When You use any of the services provided by Us through the Platform, including but not limited to, (e.g. Product Reviews, Seller Reviews), You will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use. We reserve the right, at Our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time without any prior written notice to You. It is Your responsibility to review these Terms of Use periodically for updates / changes. Your continued use of the Platform following the posting of changes will mean that You accept and agree to the revisions. As long as You comply with these Terms of Use, We grant You a personal, non-exclusive, non-transferable, limited privilege to enter and use the Platform.<br>
                
               </p>
        </div>
        
        </div>
        
    </div>





    <div class="about-down-container" >
        <div class="about-down">
            <h1 style="text-align: left;">Shipping</h1>
            <p>
                What are the delivery charges?<br><br>
                
                Delivery charge varies with each Seller. 
                
                Sellers incur relatively higher shipping costs on low value items. In such cases, charging a nominal delivery charge helps them offset logistics costs. Please check your order summary to understand the delivery charges for individual products.<br>
                
                For Products listed as F-Assured a Rs 40 charge for delivery per item is applied if the order value is less than Rs 500. While, orders of Rs 500 or above are delivered free.<br><br>
                
                Why does the delivery date not correspond to the delivery timeline of X-Y business days?<br><br>
                
                It is possible that the Seller or our courier partners have a holiday between the day your placed your order and the date of delivery, which is based on the timelines shown on the product page. In this case, we add a day to the estimated date. Some courier partners and Sellers do not work on Sundays and this is factored in to the delivery dates.<br><br>
                
                What is the estimated delivery time?<br><br>
                
                Sellers generally procure and ship the items within the time specified on the product page. Business days exclude public holidays and Sundays.<br>
                
                Estimated delivery time depends on the following factors:<br>
                
                
                </p>
        </div>
        
        </div>
        
    </div>

    
</div>




    <div class="about-down-container" >
        <div class="about-down">
            <h1 style="text-align: left;">Privacy & Policy</h1>
            <p>
                We value the trust you place in us and recognize the importance of secure transactions and information privacy. This Privacy Policy describes how Flipkart Internet Private Limited and its affiliates collect, use, share or otherwise process your personal information through Luxury Pen- Ecommerce website www.Luxury Pen- Ecommerce.com, its mobile application.. <br><br>

                By visiting the Platform, providing your information or availing our product/service, you expressly agree to be bound by the terms and conditions of this Privacy Policy, the Terms of Use and the applicable service/product terms and conditions. If you do not agree, please do not access or use our Platform.<br><br>
                
                <h2>1. Collection of Your Information</h2> <br>
                
                When you use our Platform, we collect and store your information which is provided by you from time to time. In general, you can browse the Platform without telling us who you are or revealing any personal information about yourself. Once you give us your personal information, you are not anonymous to us. Where possible, we indicate which fields are required and which fields are optional. You always have the option to not provide information by choosing not to use a particular service, product or feature on the Platform. <br><br>
                
                We may track your buying behaviour, preferences, and other information that you choose to provide on our Platform. We use this information to do internal research on our users' demographics, interests, and behaviour to better understand, protect and serve our users. This information is compiled and analysed on an aggregated basis. This information may include the URL that you just came from (whether this URL is on our Platform or not), which URL you next go to (whether this URL is on our Platform or not), your computer browser information, and your IP address.
                
                <br><br>
                
                <h2>2. Use of Demographic / Profile Data / Your Information</h2><br>
                
                We use your personal information to provide the product and services you request. To the extent we use your personal information to market to you, we will provide you the ability to opt-out of such uses. We use your personal information to assist sellers and business partners in handling and fulfilling orders; enhancing customer experience; resolve disputes; troubleshoot problems; help promote a safe service; collect money; measure consumer interest in our products and services; inform you about online and offline offers, products, services, and updates; customize and enhance your experience; detect and protect us against error, fraud and other criminal activity; enforce our terms and conditions; and as otherwise described to you at the time of collection of information.<br><br>
                
                With your consent, we will have access to your SMS, contacts in your directory, location and device information. We may also request you to provide your PAN, GST Number, Government issued ID cards/number and Know-Your-Customer (KYC) details to: (i) check your eligibility for certain products and services including but not limited to credit and payment products; (ii) issue GST invoice for the products and services purchased for your business requirements; (iii) enhance your experience on the Platform and provide you access to the products and services being offered by us, sellers, affiliates or lending partners. You understand that your access to these products/services may be affected in the event consent is not provided to us.<br><br>
              
                
                <h2>3. Cookies</h2><br>
                
                We use data collection devices such as "cookies" on certain pages of the Platform to help analyse our web page flow, measure promotional effectiveness, and promote trust and safety. "Cookies" are small files placed on your hard drive that assist us in providing our services. Cookies do not contain any of your personal information. We offer certain features that are only available through the use of a "cookie". We also use cookies to allow you to enter your password less frequently during a session. Cookies can also help us provide information that is targeted to your interests. Most cookies are "session cookies," meaning that they are automatically deleted from your hard drive at the end of a session.<br><br>
                
                You are always free to decline/delete our cookies if your browser permits, although in that case you may not be able to use certain features on the Platform and you may be required to re-enter your password more frequently during a session. Additionally, you may encounter "cookies" or other similar devices on certain pages of the Platform that are placed by third parties. We do not control the use of cookies by third parties. We use cookies from third-party partners such as Google Analytics for marketing and analytical purposes. Google Analytics help us understand how our customers use the site.
                <br><br>
                
                <h2>4. Sharing of personal information</h2><br>
                
                We may share personal information with our other corporate entities and affiliates for purposes of providing products and services offered by them, such as, the deferred payment options Flipkart PayLater offered by Flipkart Advanz Private Limited through its lending partners. These entities and affiliates may share such information with their affiliates, business partners and other third parties for the purpose of providing you their products and services, and may market to you as a result of such sharing unless you explicitly opt-out.<br><br>
                
                We may disclose your personal information to third parties, such as sellers, business partners. This disclosure may be required for us to provide you access to our products and services; for fulfilment of your orders; for enhancing your experience; for providing feedback on products; to collect payments from you; to comply with our legal obligations; to conduct market research or surveys; to enforce our Terms of Use; to facilitate our marketing and advertising activities; to analyse data; for customer service assistance; to prevent, detect, mitigate, and investigate fraudulent or illegal activities related to our product and services. We do not disclose your personal information to third parties for their marketing and advertising purposes without your explicit consent.<br><br>
               
               
                
                
                
               <h2> 5. Security Precautions</h2><br>
                
                We maintain reasonable physical, electronic and procedural safeguards to protect your information. Whenever you access your account information, we offer the use of a secure server. Once your information is in our possession we adhere to our security guidelines to protect it against unauthorized access. However, by using the Platform, the users accept the inherent security implications of data transmission over the internet and the World Wide Web which cannot always be guaranteed as completely secure, and therefore, there would always remain certain inherent risks regarding use of the Platform. Users are responsible for ensuring the protection of login and password records for their account.<br><br>
                
  
         
                
                <h2>6. Changes to this Privacy Policy</h2><br>
                
                Please check our Privacy Policy periodically for changes. We may update this Privacy Policy to reflect changes to our information practices. We will alert you to significant changes by posting the date our policy got last updated, placing a notice on our Platform, or by sending you an email when we are required to do so by applicable law.
                
               
        </div>
        </div>
    </div>  
    
</main>


    <!-- Footer section -->
    <?php
        require("footer.php");
    ?> 
</body>
</html>